### ISSUE TITLE
Endpoint GET /rearrangement/<id> doesn't return correct ADC schema

### ISSUE THREAD

**Issue by Ross65536** [sfu-ireceptor/service-php-mongodb#197]
For example:
```bash
curl --location --request GET 'localhost:80/airr/v1/rearrangement/5e53dead4d808a03178c7891'
``` 

returns:
```json
{
    "Info": {
        "Title": "AIRR Data Commons API",
        "description": "API response for repertoire query",
        "version": 1.3,
        "contact": {
            "name": "AIRR Community",
            "url": "https://github.com/airr-community"
        }
    },
    "Rearrangement": {
        "sequence_id": "SRR4084215.182 FCC3J1LACXX:1:1101:20844:1797 length=76",
        "sequence": "CTAAATCTCCAGACA...",
        "... other fields": null
    }
}
``` 

The "Rearrangement" field of the response should be an array containing one object and not the object itself

**Comment by bcorrie** [comment]
Thanks @Ross65536 we are confirming that is what we want from an AIRR spec perspective and will fix when confirmed...

**Comment by bcorrie** [comment]
@Ross65536 fix for this is on the master branch of the repo. If you are using the Turnkey on the master branch then you should get the new container by just running scripts/update_turnkey.sh
